### ISSUE TITLE
Installation on Solus OS

### ISSUE THREAD

**Issue by cavaughankirov** [intezer/linux-explorer#2]
Trying to see if I can get LEM to run on Solus OS. Think I got everything to install, however, when I run the python script (btw, had no problem getting it installed and running on a Debian system), I get the following error:
Traceback (most recent call last):
  File "linux_explorer.py", line 13, in <module>
    from flask import Flask, jsonify, send_file, send_from_directory, render_template, request, abort, redirect
ImportError: No module named flask

However, when I did the pip install requirements.txt (something like that) it stated:

Successfully installed Flask-0.12.2 Jinja2-2.10 MarkupSafe-1.0 OTXv2-1.2 Werkzeug-0.12.2 certifi-2017.11.5 chardet-3.0.4 click-6.7 idna-2.6 itsdangerous-0.24 requests-2.18.4 simplejson-3.12.0 urllib3-1.22

So flask is apparently installed, but linux-explorer is not finding it. Any ideas?

**Comment by davidt99** [comment]
Are you using virtualenv? When running `sudo python ...` the python interpreter is the root's. Try running pip with `sudo` or run the virtualenv's  python interpreter.
Other option is that pip pointing to python3 and python is pointing to python2 (or vise-versa). Run pip2 and python2 recpectivly.

**Comment by cavaughankirov** [comment]
Not with virtualenv. And I did run it with sudo. Ran pip2 and now when I try to run it's complaining that Yara isn't installed...

**Comment by davidt99** [comment]
Have you installed YARA on your machine? Try to install it using solus package manager.

**Comment by cavaughankirov** [comment]
No I had Yara installed, but not in the PATH. So I fixed that. Unfortunately neither yara nor chkrootkit are available via the Solus package manager. Yara I compiled and got to work. But chkrootkit requires netstat and I can't seem to get netstat installed. Trying to install net-tools, but it won't install either (have to compile it as well!). Anyhow, none of this is your problem. THANKS!

**Comment by davidt99** [comment]
If you are interested in other linux explorer features, you can create a PR making  yara and chkrootkit optional.
I'm going to keep this issue open for future reference.

**Comment by cavaughankirov** [comment]
commented out chkrootkit and it worked! Why didn't I think about that?!

**Comment by omri9741** [comment]
Fixed. Also from now Linux Expl0rer auto-install chkrootkit( & YARA).

> https://github.com/intezer/linux-explorer/commit/4ef4aff1565692200d000e239392c8de6f1232ce
