### ISSUE TITLE
error :YARA not installed

### ISSUE THREAD

**Issue by donlino97** [intezer/linux-explorer#7]
hi
I did all what you said to do in Readme
and im stick in the error :YARA not installed
this is what i got `[*] starting Linux Expl0rer...
Traceback (most recent call last):
  File "linux_explorer.py", line 23, in <module>
    toolbox = dict({'yara': tools.YARA(),
  File "/root/Desktop/linux-explorer-master/tools.py", line 16, in __init__
    raise Exception('error: %s not installed' % self.__class__.__name__)
Exception: error: YARA not installed
`
can anyone help me with this issue please

**Comment by davidt99** [comment]
Hi, @donlino97, do you have yara executable installed on your machine?

**Comment by donlino97** [comment]
hi @davidt99 
i have installed yara directly through apt package 
and if i write in the cmd prompt `yara -h` it works so yes its executable 
i saw many people have  same problems so if you have any idea im thankful
In the  **tools.py** file there is an **if** function `if not self._is_installed()`
i tried to remove it and the explorer opens but doesnt work succesfully it still have some issues 
thank you

**Comment by Jon045** [comment]
Hello, 

I am having the same problem. Any suggested solutions?

**Comment by davidt99** [comment]
@donlino97 @Jon045 I've deployed a fix, please run the deploy script again and report back if that resolved your issue.

**Comment by donlino97** [comment]
It works very well... 
Thank you 👍🏻
